// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBREn9e29fkYiuek-jtdzjFTH2biVw2dx4',
    appId: '1:895981865559:web:e2e1001780b752e647f112',
    messagingSenderId: '895981865559',
    projectId: 'fluttermovies-656fe',
    authDomain: 'fluttermovies-656fe.firebaseapp.com',
    storageBucket: 'fluttermovies-656fe.appspot.com',
    measurementId: 'G-R1VDSVV20D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsaV4bmZJKguA_a2XgrhK4wljeClYbC80',
    appId: '1:895981865559:android:df87b619b41814b547f112',
    messagingSenderId: '895981865559',
    projectId: 'fluttermovies-656fe',
    storageBucket: 'fluttermovies-656fe.appspot.com',
  );
}
